54 connector widget special chars
ploomber/jupysql-plugin pull request #83
Opened 2023-09-25 23:54 UTC by bryannho

## Describe your changes
- Fixed bug that broke `connect` and `delete` button in `ConnectorWidget` when special characters were included in the alias
- Added `src/util/helper-functions.ts` to hold string formatting function for special characters

## Issue number

Closes #54 

## Checklist before requesting a review

- [ ] Performed a self-review of my code
- [ ] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [ ] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [ ] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

2023-09-26 00:43 UTC, bryannho commented
CI seems to be failing for unknown reason, possibly related to issue #78

2023-09-29 00:22 UTC, edublancas commented
@bryannho is this ready? don't forget to explicitly ask for a review. are you able to request reviews?

![image](https://github.com/ploomber/jupysql-plugin/assets/989250/1c2c33b8-70f4-4d06-9f22-700685e8da0a)

if you can't, you can tag me and say "ready for review" so I get notified

2023-09-29 02:20 UTC, bryannho commented
> @bryannho is this ready? don't forget to explicitly ask for a review. are you able to request reviews?
> 
> ![image](https://user-images.githubusercontent.com/989250/271443857-1c2c33b8-70f4-4d06-9f22-700685e8da0a.png)
> 
> if you can't, you can tag me and say "ready for review" so I get notified

Apologies - this is ready to review. I marked the branch as ready but I'm not able to request reviews in the sidebar. Will tag you next time

2023-09-29 04:53 UTC, edublancas requested changes
a few things are missing:

- changelog entry
- explain your solution in the PR description
- unit tests

2023-09-29 04:53 UTC, edublancas commented on src/utils/helper-functions.ts
> +export const specialToASCII = (str: string): string => {
please add a docstring

2023-10-02 18:18 UTC, bryannho commented
> a few things are missing:
> 
> * changelog entry
> * explain your solution in the PR description
> * unit tests

Added [changelog](https://github.com/ploomber/jupysql-plugin/pull/83/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR3-R8), PR description, and [unit tests](https://github.com/ploomber/jupysql-plugin/pull/83/files#diff-d402d55ba98d93aba9ceb061c57c0611ff5831e26eb3523ed45b33e951bd1f13R649-R698)

2023-10-02 20:59 UTC, edublancas commented
@bryannho what's the status here? are you gonna tackle the CI issue first or will you work on passing the CI here first?

2023-10-02 22:01 UTC, bryannho commented
> @bryannho what's the status here? are you gonna tackle the CI issue first or will you work on passing the CI here first?

I'm working on passing the CI here first. Once I get that done I'll mark it for your review and start working on the CI issue. Apologies I've been working through some hardware issues with my machine but I should be have this ready for review by tomorrow morning!

2023-10-03 01:29 UTC, edublancas commented
sounds good!

2023-10-03 14:33 UTC, bryannho commented
@edublancas I was able to get my own individual tests to work, but the PR keeps failing checks as a result of the CI issue with multiple tries. Might need to pivot to fixing the CI issue first and then come back around to this PR.

2024-07-18 17:35 UTC, closed without merging